// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "TableGenBackends.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Record.h"
#include <iterator>

using namespace llvm;

void clang::EmitRISCVBoscZttHeader(const RecordKeeper &Records, raw_ostream &OS) {
  OS << "/* Generated by clang-tblgen. Do not edit. */\n"
        "#ifndef __RISCV_BOSC_ZTT_H\n#define __RISCV_BOSC_ZTT_H\n\n"
        "#if !defined(__riscv) || !defined(__riscv_boscztt)\n"
        "#error RISCVBoscZtt.h requires the RISC-V boscztt extension\n"
        "#else\n\n"
        "/* Opaque register values containing profile-dependent element squares.\n"
        " * _xN specifies N squares; the default M type includes all packed\n"
        " * squares. ACC defaults to one square. No RVV dependency. */\n";
#define BOSCZTT_TYPE(Name, Id, SingletonId) \
  OS << "typedef " << Name << ' ' << StringRef(Name).drop_front(2) << ";\n";
#include "clang/Basic/RISCVBoscZttTypes.def"

  OS << R"ztt(
/* Descriptor values from Ztt v0.6, section 2.4. Integer signedness and
 * floating-point encoding are runtime state, not C scalar conversions. */
#define BOSCZTT_INT_SAT (1UL << 29)
#define BOSCZTT_INT_RNU (0UL << 27)
#define BOSCZTT_INT_RNE (1UL << 27)
#define BOSCZTT_INT_RDN (2UL << 27)
#define BOSCZTT_INT_ROD (3UL << 27)
#define BOSCZTT_FP_RNE (0UL << 22)
#define BOSCZTT_FP_RTZ (1UL << 22)
#define BOSCZTT_FP_RDN (2UL << 22)
#define BOSCZTT_FP_RUP (3UL << 22)
#define BOSCZTT_FP_RMM (4UL << 22)
#define BOSCZTT_FP_RNO (5UL << 22)
#define BOSCZTT_DTYPE_F16 0x14300110UL
#define BOSCZTT_DTYPE_BF16 0x20300110UL
#define BOSCZTT_DTYPE_F32 0x20300120UL
#define BOSCZTT_DTYPE_F64 0x2c300140UL
#define BOSCZTT_DTYPE_FP8_E4M3 0x10100108UL
#define BOSCZTT_DTYPE_FP8_E5M2 0x14300108UL
)ztt";
  for (unsigned Width : {4, 8, 16, 32, 64, 128}) {
    OS << "#define BOSCZTT_DTYPE_U" << Width << ' ' << Width << "UL\n";
    OS << "#define BOSCZTT_DTYPE_I" << Width << " (0x40000000UL | "
       << Width << "UL)\n";
  }
  OS << "\n/* Storage aliases: program the matching descriptor with msettyp or\n"
        " * asettyp before arithmetic. FP8 has i8 IR storage; it has no implicit\n"
        " * integer-to-float conversion. Profile/group limits still apply. */\n";
#define BOSCZTT_TYPE(Name, Id, SingletonId)                                    \
  {                                                                          \
    StringRef Public = StringRef(Name).drop_front(2);                          \
    size_t Pos = Public.find("_i");                                          \
    if (Pos != StringRef::npos) {                                             \
      OS << "typedef " << Public << ' ' << Public.take_front(Pos) << "_u"    \
         << Public.drop_front(Pos + 2) << ";\n";                            \
      if (Public.substr(Pos + 2).starts_with("8_"))                          \
        for (StringRef Format : {"fp8_e4m3", "fp8_e5m2"})                    \
          OS << "typedef " << Public << ' ' << Public.take_front(Pos + 1)   \
             << Format << Public.drop_front(Pos + 3) << ";\n";              \
    }                                                                        \
  }
#include "clang/Basic/RISCVBoscZttTypes.def"
  OS << "\n/* The compiler provides these polymorphic builtin functions.\n"
        " * Matrix-writing functions take a writable destination variable\n"
        " * first and return void. zip/unzip update both arguments.\n"
        " * Scalar results have type unsigned long (XLEN). */\n";
  // Use the LLVM inventory for the documented operand order and assert that
  // every instruction has a corresponding Clang builtin record.
  struct Builtin {
    const char *Name;
    const char *Form;
    const char *Signature;
  };
  static constexpr Builtin Builtins[] = {
#define RISCV_ZTT_INTRINSIC(NAME, OPCODE, FORM, SIG) {#NAME, #FORM, SIG},
#include "llvm/IR/IntrinsicsRISCVBoscZtt.def"
#undef RISCV_ZTT_INTRINSIC
  };
  assert(Records.getAllDerivedDefinitions("BoscZttBuiltin").size() ==
         std::size(Builtins));
  for (const auto &B : Builtins) {
    assert(Records.getDef(B.Name) && "missing boscztt builtin");
    StringRef Form = B.Form, Signature = B.Signature;
    bool ScalarResult = Form == "acquire" || Form == "get" || Form == "extract";
    OS << "/* " << (ScalarResult ? "unsigned long " : "void ") << B.Name << '(';
    if (ScalarResult)
      Signature = Signature.drop_front();
    for (unsigned I = 0; I < Signature.size(); ++I) {
      if (I)
        OS << ", ";
      switch (Signature[I]) {
      case 'M': OS << "M"; break;
      case 'A': OS << "ACC"; break;
      case 'X': OS << "unsigned long"; break;
      case 'P': OS << (Form == "store" ? "void *" : "const void *"); break;
      }
      if ((I == 0 && (Form == "matrix" || Form == "set")) || Form == "zip")
        OS << " destination" << I;
    }
    if (Signature.empty())
      OS << "void";
    OS << "); */\n";
  }
  OS << "\n#endif /* boscztt */\n#endif /* __RISCV_BOSC_ZTT_H */\n";
}
